<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();
global $arrFilter;

if($arParams["COMPONENT_TYPE"] == "union_name"){
	$APPLICATION->IncludeComponent(
		"sp-artgroup:unionproduct.name",
		"",
		array(),
		$component
	);
}

if($arParams["COMPONENT_TYPE"] == "union_manufact"){
	$APPLICATION->IncludeComponent(
		"sp-artgroup:unionproduct.manufact",
		"",
		array(
			"SEF_FOLDER" => $arParams["SEF_FOLDER"],
		),
		$component
	);
}

$arrFilter['ID'] = $GLOBALS['filter_product'];

$APPLICATION->ShowViewContent('top_text');

$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	".default",
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CUSTOM_FILTER" => "",
		"DETAIL_URL" => "/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "1",
		"IBLOCK_TYPE" => "tvoyaapteka",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "orange",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => ($_SESSION["count"] != '')?$_SESSION["count"]:20,
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => $_SESSION["GEOIP"]["PRICE_TYPE"]["FILTER"],
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_SUBSCRIPTION" => "N",
		"PROPERTY_CODE" => array(
			0 => "PRESCRIPTION",
			1 => "IS_PRESCRIPTION",
			2 => "HOT_PRICE",
			3 => "NOT_SPEC",
		),
		"SECTION_CODE" => "",
		"SECTION_CODE_PATH" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "#SECTION_CODE#/",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "Y",
		"SEF_RULE" => "",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_CLOSE_POPUP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"STORES" => array(
			0 => "5",
			1 => "6",
			2 => "7",
			3 => "8",
			4 => "9",
			5 => "10",
			6 => "11",
			7 => "12",
			8 => "13",
			9 => "14",
			10 => "15",
			11 => "16",
			12 => "17",
			13 => "18",
			14 => "19",
			15 => "20",
			16 => "21",
			17 => "22",
			18 => "23",
			19 => "24",
			20 => "26",
			21 => "27",
			22 => "28",
			23 => "29",
			24 => "31",
			25 => "32",
			26 => "33",
			27 => "34",
			28 => "35",
			29 => "36",
			30 => "37",
			31 => "38",
			32 => "39",
			33 => "40",
			34 => "41",
			35 => "42",
			36 => "43",
			37 => "44",
			38 => "45",
			39 => "46",
			40 => "47",
			41 => "48",
			42 => "49",
			43 => "50",
			44 => "51",
			45 => "52",
			46 => "53",
			47 => "54",
			48 => "55",
			49 => "56",
			50 => "57",
			51 => "58",
			52 => "59",
			53 => "60",
			54 => "61",
			55 => "62",
			56 => "63",
			57 => "65",
			58 => "66",
			59 => "67",
			60 => "68",
			61 => "69",
			62 => "70",
			63 => "71",
			64 => "72",
			65 => "73",
			66 => "74",
			67 => "75",
			68 => "76",
			69 => "77",
			70 => "78",
			71 => "79",
			72 => "80",
			73 => "81",
			74 => "82",
			75 => "83",
			76 => "84",
			77 => "85",
			78 => "86",
		),
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_FILTER" => "Y",
		"STORE_PATH" => "/store/#store_id#",
		// для корректной работы кеша компонента
		"STORE_GET"     => $_REQUEST['store'],
		"STORE_GLOBAL"  => $GLOBALS['default_store'],
		"CITY"          => $_SESSION['GEOIP']['D_CITY_ID'],
		"ALL_DAY_STORE" => $GLOBALS['all_day_store'],
		"COMPONENT_TEMPLATE" => ".default"
	),
	false
);
$APPLICATION->ShowViewContent('bottom_text');